"""se agrega el campo de room_name a la tabla room

Revision ID: 6999bf4976d9
Revises: ce8424de8295
Create Date: 2025-08-19 18:17:29.203734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6999bf4976d9'
down_revision: Union[str, None] = 'ce8424de8295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('room_name', sa.String(length=50), nullable=False, server_default="-"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'room_name')
    # ### end Alembic commands ###
