"""se ajusta el campo status de availability y los enum

Revision ID: 88f86b87c952
Revises: a3a8f8a9793b
Create Date: 2025-08-21 16:14:52.223589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88f86b87c952'
down_revision: Union[str, None] = 'a3a8f8a9793b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    availability_status = sa.Enum(
        'available',
        'busy',
        'not_available',
        name='availabilitystatus'
    )
    availability_status.create(op.get_bind(), checkfirst=True)

    # Agregar columna con default válido
    op.add_column(
        'availabilities',
        sa.Column(
            'status',
            availability_status,
            server_default=sa.text("'available'"),
            nullable=False
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('availabilities', 'status')
    # ### end Alembic commands ###
