"""se ajusta el modelo de booking para agregar el campo start_hour, end_hour. ademas de agregar el campo status en el modelo de availability

Revision ID: a3a8f8a9793b
Revises: 6999bf4976d9
Create Date: 2025-08-21 15:26:31.249211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3a8f8a9793b'
down_revision: Union[str, None] = '6999bf4976d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Crear tipo ENUM primero
    availability_status = sa.Enum(
        'Available',
        'Busy',
        'Not Available',
        name='availabilitystatus'
    )
    availability_status.create(op.get_bind(), checkfirst=True)

    # Agregar columna con default válido
    op.add_column(
        'availabilities',
        sa.Column(
            'status',
            availability_status,
            server_default=sa.text("'Available'"),
            nullable=False
        )
    )

    op.add_column('bookings', sa.Column('start_hour', sa.String(
        length=20), server_default='', nullable=False))
    op.add_column('bookings', sa.Column('end_hour', sa.String(
        length=20), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'end_hour')
    op.drop_column('bookings', 'start_hour')
    op.drop_column('availabilities', 'status')
    # ### end Alembic commands ###
