"""booking models whitelist

Revision ID: aec1a6e904a7
Revises: 6325590f4203
Create Date: 2025-08-09 13:49:22.405120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aec1a6e904a7'
down_revision: Union[str, None] = '6325590f4203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accommodations', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('accommodations', 'pet_friendly',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               nullable=False)
    op.alter_column('accommodations', 'type',
               existing_type=sa.VARCHAR(),
               server_default='-',
               existing_nullable=False)
    op.alter_column('accommodations', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default='true',
               existing_nullable=False)
    op.create_index(op.f('ix_accommodations_host_id'), 'accommodations', ['host_id'], unique=False)
    op.create_index(op.f('ix_accommodations_id'), 'accommodations', ['id'], unique=False)
    op.create_index(op.f('ix_accommodations_location'), 'accommodations', ['location'], unique=False)
    op.create_index('ix_accommodations_location_name', 'accommodations', ['location', 'name'], unique=False)
    op.create_index(op.f('ix_accommodations_name'), 'accommodations', ['name'], unique=False)
    op.create_unique_constraint('uq_accommodations_host_name_location', 'accommodations', ['host_id', 'name', 'location'])
    op.drop_constraint('accommodations_host_id_fkey', 'accommodations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_accommodations_host_id_user'), 'accommodations', 'user', ['host_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_availabilities_date'), 'availabilities', ['date'], unique=False)
    op.create_index(op.f('ix_availabilities_id'), 'availabilities', ['id'], unique=False)
    op.create_index(op.f('ix_availabilities_room_id'), 'availabilities', ['room_id'], unique=False)
    op.create_index('ix_availability_room_date', 'availabilities', ['room_id', 'date'], unique=False)
    op.create_unique_constraint('uq_availability_room_date', 'availabilities', ['room_id', 'date'])
    op.drop_constraint('availabilities_room_id_fkey', 'availabilities', type_='foreignkey')
    op.create_foreign_key(op.f('fk_availabilities_room_id_rooms'), 'availabilities', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.add_column('bookings', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('bookings', 'guests',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'cancelled', 'completed', name='bookingstatus'),
               server_default='pending',
               existing_nullable=False)
    op.drop_constraint('bookings_code_key', 'bookings', type_='unique')
    op.create_index('ix_booking_room_dates', 'bookings', ['room_id', 'start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_bookings_code'), 'bookings', ['code'], unique=True)
    op.create_index(op.f('ix_bookings_end_date'), 'bookings', ['end_date'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_room_id'), 'bookings', ['room_id'], unique=False)
    op.create_index(op.f('ix_bookings_start_date'), 'bookings', ['start_date'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_unique_constraint('uq_booking_code', 'bookings', ['code'])
    op.drop_constraint('bookings_user_id_fkey', 'bookings', type_='foreignkey')
    op.drop_constraint('bookings_room_id_fkey', 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bookings_user_id_user'), 'bookings', 'user', ['user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_bookings_room_id_rooms'), 'bookings', 'rooms', ['room_id'], ['id'], ondelete='RESTRICT')
    op.create_index('ix_image_accommodation', 'images', ['accommodation_id'], unique=False)
    op.create_index('ix_image_room', 'images', ['room_id'], unique=False)
    op.create_index(op.f('ix_images_accommodation_id'), 'images', ['accommodation_id'], unique=False)
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_index(op.f('ix_images_room_id'), 'images', ['room_id'], unique=False)
    op.drop_constraint('images_room_id_fkey', 'images', type_='foreignkey')
    op.drop_constraint('images_accommodation_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(op.f('fk_images_accommodation_id_accommodations'), 'images', 'accommodations', ['accommodation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_images_room_id_rooms'), 'images', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.alter_column('rooms', 'is_available',
               existing_type=sa.BOOLEAN(),
               server_default='true',
               nullable=False)
    op.alter_column('rooms', 'beds',
               existing_type=sa.INTEGER(),
               server_default='1',
               existing_nullable=False)
    op.create_index('ix_rooms_accommodation_available', 'rooms', ['accommodation_id', 'is_available'], unique=False)
    op.create_index(op.f('ix_rooms_accommodation_id'), 'rooms', ['accommodation_id'], unique=False)
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_index(op.f('ix_rooms_room_type'), 'rooms', ['room_type'], unique=False)
    op.create_unique_constraint('uq_rooms_accommodation_room_type', 'rooms', ['accommodation_id', 'room_type'])
    op.drop_constraint('rooms_accommodation_id_fkey', 'rooms', type_='foreignkey')
    op.create_foreign_key(op.f('fk_rooms_accommodation_id_accommodations'), 'rooms', 'accommodations', ['accommodation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_rooms_accommodation_id_accommodations'), 'rooms', type_='foreignkey')
    op.create_foreign_key('rooms_accommodation_id_fkey', 'rooms', 'accommodations', ['accommodation_id'], ['id'])
    op.drop_constraint('uq_rooms_accommodation_room_type', 'rooms', type_='unique')
    op.drop_index(op.f('ix_rooms_room_type'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_accommodation_id'), table_name='rooms')
    op.drop_index('ix_rooms_accommodation_available', table_name='rooms')
    op.alter_column('rooms', 'beds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('rooms', 'is_available',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.drop_constraint(op.f('fk_images_room_id_rooms'), 'images', type_='foreignkey')
    op.drop_constraint(op.f('fk_images_accommodation_id_accommodations'), 'images', type_='foreignkey')
    op.create_foreign_key('images_accommodation_id_fkey', 'images', 'accommodations', ['accommodation_id'], ['id'])
    op.create_foreign_key('images_room_id_fkey', 'images', 'rooms', ['room_id'], ['id'])
    op.drop_index(op.f('ix_images_room_id'), table_name='images')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_index(op.f('ix_images_accommodation_id'), table_name='images')
    op.drop_index('ix_image_room', table_name='images')
    op.drop_index('ix_image_accommodation', table_name='images')
    op.drop_constraint(op.f('fk_bookings_room_id_rooms'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('fk_bookings_user_id_user'), 'bookings', type_='foreignkey')
    op.create_foreign_key('bookings_room_id_fkey', 'bookings', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key('bookings_user_id_fkey', 'bookings', 'user', ['user_id'], ['id'])
    op.drop_constraint('uq_booking_code', 'bookings', type_='unique')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_start_date'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_room_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_end_date'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_code'), table_name='bookings')
    op.drop_index('ix_booking_room_dates', table_name='bookings')
    op.create_unique_constraint('bookings_code_key', 'bookings', ['code'])
    op.alter_column('bookings', 'status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'cancelled', 'completed', name='bookingstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('bookings', 'guests',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('bookings', 'created_at')
    op.drop_constraint(op.f('fk_availabilities_room_id_rooms'), 'availabilities', type_='foreignkey')
    op.create_foreign_key('availabilities_room_id_fkey', 'availabilities', 'rooms', ['room_id'], ['id'])
    op.drop_constraint('uq_availability_room_date', 'availabilities', type_='unique')
    op.drop_index('ix_availability_room_date', table_name='availabilities')
    op.drop_index(op.f('ix_availabilities_room_id'), table_name='availabilities')
    op.drop_index(op.f('ix_availabilities_id'), table_name='availabilities')
    op.drop_index(op.f('ix_availabilities_date'), table_name='availabilities')
    op.drop_constraint(op.f('fk_accommodations_host_id_user'), 'accommodations', type_='foreignkey')
    op.create_foreign_key('accommodations_host_id_fkey', 'accommodations', 'user', ['host_id'], ['id'])
    op.drop_constraint('uq_accommodations_host_name_location', 'accommodations', type_='unique')
    op.drop_index(op.f('ix_accommodations_name'), table_name='accommodations')
    op.drop_index('ix_accommodations_location_name', table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_location'), table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_id'), table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_host_id'), table_name='accommodations')
    op.alter_column('accommodations', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('accommodations', 'type',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('accommodations', 'pet_friendly',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.drop_column('accommodations', 'created_at')
    # ### end Alembic commands ###
