"""se agregan los campos de telefono, direccion, calificacion y correo a la tabla de accommodations

Revision ID: ce8424de8295
Revises: dc04a5585af1
Create Date: 2025-08-15 16:50:21.298874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce8424de8295'
down_revision: Union[str, None] = 'dc04a5585af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accommodations', sa.Column('phone_number', sa.String(length=255), server_default='', nullable=False))
    op.add_column('accommodations', sa.Column('email', sa.String(length=255), server_default='', nullable=False))
    op.add_column('accommodations', sa.Column('addres', sa.String(length=255), server_default='', nullable=False))
    op.add_column('accommodations', sa.Column('stars', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accommodations', 'stars')
    op.drop_column('accommodations', 'addres')
    op.drop_column('accommodations', 'email')
    op.drop_column('accommodations', 'phone_number')
    # ### end Alembic commands ###
