"""change unique locations

Revision ID: dc04a5585af1
Revises: f0d5c58a6e48
Create Date: 2025-08-12 23:50:35.570872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc04a5585af1'
down_revision: Union[str, None] = 'f0d5c58a6e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_accommodations_location_name', table_name='accommodations')
    op.drop_constraint('uq_accommodations_host_name_location', 'accommodations', type_='unique')
    op.create_unique_constraint('uq_accommodations_host_name', 'accommodations', ['host_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_accommodations_host_name', 'accommodations', type_='unique')
    op.create_unique_constraint('uq_accommodations_host_name_location', 'accommodations', ['host_id', 'name', 'location'])
    op.create_index('ix_accommodations_location_name', 'accommodations', ['location', 'name'], unique=False)
    # ### end Alembic commands ###
