"""init

Revision ID: f0d5c58a6e48
Revises: 
Create Date: 2025-08-11 15:10:36.132378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0d5c58a6e48'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('services', sa.String(length=255), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('pet_friendly', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('type', sa.String(length=50), server_default='-', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['user.id'], name=op.f('fk_accommodations_host_id_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accommodations')),
    sa.UniqueConstraint('host_id', 'name', name='uq_accommodations_host_name')
    )
    op.create_index(op.f('ix_accommodations_host_id'), 'accommodations', ['host_id'], unique=False)
    op.create_index(op.f('ix_accommodations_id'), 'accommodations', ['id'], unique=False)
    op.create_index(op.f('ix_accommodations_location'), 'accommodations', ['location'], unique=False)
    op.create_index('ix_accommodations_location_name', 'accommodations', ['location', 'name'], unique=False)
    op.create_index(op.f('ix_accommodations_name'), 'accommodations', ['name'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('amenities', sa.String(length=255), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('beds', sa.Integer(), server_default='1', nullable=False),
    sa.Column('accommodation_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('base_price >= 0', name=op.f('ck_rooms_ck_rooms_base_price_non_negative')),
    sa.CheckConstraint('beds > 0', name=op.f('ck_rooms_ck_rooms_beds_positive')),
    sa.CheckConstraint('capacity > 0', name=op.f('ck_rooms_ck_rooms_capacity_positive')),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], name=op.f('fk_rooms_accommodation_id_accommodations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms')),
    sa.UniqueConstraint('accommodation_id', 'room_type', name='uq_rooms_accommodation_room_type')
    )
    op.create_index('ix_rooms_accommodation_available', 'rooms', ['accommodation_id', 'is_available'], unique=False)
    op.create_index(op.f('ix_rooms_accommodation_id'), 'rooms', ['accommodation_id'], unique=False)
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_index(op.f('ix_rooms_room_type'), 'rooms', ['room_type'], unique=False)
    op.create_table('availabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('price > 0', name=op.f('ck_availabilities_ck_availability_price_positive')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_availabilities_room_id_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availabilities')),
    sa.UniqueConstraint('room_id', 'date', name='uq_availability_room_date')
    )
    op.create_index(op.f('ix_availabilities_date'), 'availabilities', ['date'], unique=False)
    op.create_index(op.f('ix_availabilities_id'), 'availabilities', ['id'], unique=False)
    op.create_index(op.f('ix_availabilities_room_id'), 'availabilities', ['room_id'], unique=False)
    op.create_index('ix_availability_room_date', 'availabilities', ['room_id', 'date'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', 'completed', name='bookingstatus'), server_default='pending', nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date > start_date', name=op.f('ck_bookings_ck_booking_dates_valid')),
    sa.CheckConstraint('guests > 0', name=op.f('ck_bookings_ck_booking_guests_positive')),
    sa.CheckConstraint('total_price > 0', name=op.f('ck_bookings_ck_booking_price_positive')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_bookings_room_id_rooms'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_bookings_user_id_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings')),
    sa.UniqueConstraint('code', name='uq_booking_code')
    )
    op.create_index('ix_booking_room_dates', 'bookings', ['room_id', 'start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_bookings_code'), 'bookings', ['code'], unique=True)
    op.create_index(op.f('ix_bookings_end_date'), 'bookings', ['end_date'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_room_id'), 'bookings', ['room_id'], unique=False)
    op.create_index(op.f('ix_bookings_start_date'), 'bookings', ['start_date'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('accommodation_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('length(url) > 0', name=op.f('ck_images_ck_image_url_not_empty')),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], name=op.f('fk_images_accommodation_id_accommodations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_images_room_id_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images'))
    )
    op.create_index('ix_image_accommodation', 'images', ['accommodation_id'], unique=False)
    op.create_index('ix_image_room', 'images', ['room_id'], unique=False)
    op.create_index(op.f('ix_images_accommodation_id'), 'images', ['accommodation_id'], unique=False)
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_index(op.f('ix_images_room_id'), 'images', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_room_id'), table_name='images')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_index(op.f('ix_images_accommodation_id'), table_name='images')
    op.drop_index('ix_image_room', table_name='images')
    op.drop_index('ix_image_accommodation', table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_start_date'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_room_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_end_date'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_code'), table_name='bookings')
    op.drop_index('ix_booking_room_dates', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('ix_availability_room_date', table_name='availabilities')
    op.drop_index(op.f('ix_availabilities_room_id'), table_name='availabilities')
    op.drop_index(op.f('ix_availabilities_id'), table_name='availabilities')
    op.drop_index(op.f('ix_availabilities_date'), table_name='availabilities')
    op.drop_table('availabilities')
    op.drop_index(op.f('ix_rooms_room_type'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_accommodation_id'), table_name='rooms')
    op.drop_index('ix_rooms_accommodation_available', table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_accommodations_name'), table_name='accommodations')
    op.drop_index('ix_accommodations_location_name', table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_location'), table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_id'), table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_host_id'), table_name='accommodations')
    op.drop_table('accommodations')
    # ### end Alembic commands ###
